/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/addresses": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.AddressListResult"];
          };
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 地址信息 */
          request: definitions["user.CreateAddressReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.Address"];
          };
        };
      };
    };
  };
  "/api/v1/addresses/default": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.Address"];
          };
        };
      };
    };
  };
  "/api/v1/addresses/{id}": {
    get: {
      parameters: {
        path: {
          /** 地址ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.Address"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          /** 地址ID */
          id: number;
        };
        body: {
          /** 更新信息 */
          request: definitions["user.UpdateAddressReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.Address"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** 地址ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/admin/reviews/pending": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          size?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["review.ReviewListResult"];
          };
        };
      };
    };
  };
  "/api/v1/admin/reviews/{id}": {
    delete: {
      parameters: {
        path: {
          /** 评价ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/admin/reviews/{id}/moderate": {
    patch: {
      parameters: {
        path: {
          /** 评价ID */
          id: number;
        };
        body: {
          /** 审核信息 */
          request: definitions["review.ModerateReviewReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/admin/reviews/{id}/reply": {
    post: {
      parameters: {
        path: {
          /** 评价ID */
          id: number;
        };
        body: {
          /** 回复内容 */
          request: definitions["review.ReplyReviewReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/attributes": {
    get: {
      parameters: {
        query: {
          /** 类目ID */
          category_id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Attribute"][];
          };
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 属性信息 */
          attr: definitions["product.CreateAttributeReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Attribute"];
          };
        };
      };
    };
  };
  "/api/v1/attributes/searchable": {
    get: {
      parameters: {
        query: {
          /** 类目ID */
          category_id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Attribute"][];
          };
        };
      };
    };
  };
  "/api/v1/attributes/sku-spec": {
    get: {
      parameters: {
        query: {
          /** 类目ID */
          category_id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Attribute"][];
          };
        };
      };
    };
  };
  "/api/v1/attributes/{id}": {
    get: {
      parameters: {
        path: {
          /** 属性ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Attribute"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          /** 属性ID */
          id: number;
        };
        body: {
          /** 属性信息 */
          attr: definitions["product.UpdateAttributeReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Attribute"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** 属性ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: { [key: string]: string };
          };
        };
      };
    };
  };
  "/api/v1/auth/login/password": {
    post: {
      parameters: {
        body: {
          /** 登录信息 */
          request: definitions["user.PasswordLoginReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.LoginResponse"];
          };
        };
      };
    };
  };
  "/api/v1/auth/refresh": {
    post: {
      parameters: {
        body: {
          /** 刷新令牌 */
          request: definitions["user.RefreshTokenReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.TokenResponse"];
          };
        };
      };
    };
  };
  "/api/v1/auth/register": {
    post: {
      parameters: {
        body: {
          /** 注册信息 */
          request: definitions["user.RegisterReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.LoginResponse"];
          };
        };
      };
    };
  };
  "/api/v1/brands": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          size?: number;
          /** 品牌名称模糊搜索 */
          name?: string;
          /** 首字母筛选 */
          first_letter?: string;
          /** 状态 1-启用 0-禁用 */
          status?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.BrandListResult"];
          };
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 品牌信息 */
          brand: definitions["product.CreateBrandReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Brand"];
          };
        };
      };
    };
  };
  "/api/v1/brands/{id}": {
    get: {
      parameters: {
        path: {
          /** 品牌ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Brand"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          /** 品牌ID */
          id: number;
        };
        body: {
          /** 品牌信息 */
          brand: definitions["product.UpdateBrandReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Brand"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** 品牌ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: { [key: string]: string };
          };
        };
      };
    };
  };
  "/api/v1/carts": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["trade.Cart"];
          };
        };
      };
    };
    put: {
      parameters: {
        body: {
          /** 更新信息 */
          request: definitions["trade.UpdateItemReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 商品信息 */
          request: definitions["trade.AddItemReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
    delete: {
      parameters: {
        query: {
          /** SKU ID */
          sku_id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/carts/clear": {
    post: {
      parameters: {
        query: {
          /** 会话ID */
          session_id?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/categories": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          size?: number;
          /** 类目名称模糊搜索 */
          name?: string;
          /** 状态 1-启用 0-禁用 */
          status?: number;
          /** 层级 1-3 */
          level?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.CategoryListResult"];
          };
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 类目信息 */
          category: definitions["product.CreateCategoryReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Category"];
          };
        };
      };
    };
  };
  "/api/v1/categories/all": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Category"][];
          };
        };
      };
    };
  };
  "/api/v1/categories/level/{level}": {
    get: {
      parameters: {
        path: {
          /** 层级（1-3） */
          level: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Category"][];
          };
        };
      };
    };
  };
  "/api/v1/categories/root": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Category"][];
          };
        };
      };
    };
  };
  "/api/v1/categories/{id}": {
    get: {
      parameters: {
        path: {
          /** 类目ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Category"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          /** 类目ID */
          id: number;
        };
        body: {
          /** 类目信息 */
          category: definitions["product.UpdateCategoryReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Category"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** 类目ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: { [key: string]: string };
          };
        };
      };
    };
  };
  "/api/v1/categories/{id}/brands": {
    get: {
      parameters: {
        path: {
          /** 类目ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.CategoryBrandDetail"][];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          /** 类目ID */
          id: number;
        };
        body: {
          /** 品牌ID列表 */
          req: definitions["product.SetCategoryBrandsReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/categories/{id}/children": {
    get: {
      parameters: {
        path: {
          /** 父类目ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.Category"][];
          };
        };
      };
    };
  };
  "/api/v1/coupons/claim": {
    post: {
      parameters: {
        body: {
          /** 领取信息 */
          request: definitions["marketing.ClaimCouponReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/coupons/me": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          size?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["marketing.UserPromotionListResult"];
          };
        };
      };
    };
  };
  "/api/v1/coupons/use": {
    post: {
      parameters: {
        body: {
          /** 使用信息 */
          request: definitions["marketing.UseCouponReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/dashboard/stats": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["dashboard.DashboardResponse"];
          };
        };
      };
    };
  };
  "/api/v1/flash/buy": {
    post: {
      parameters: {
        body: {
          /** 抢购信息 */
          request: definitions["marketing.FlashBuyReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/flash/confirm": {
    post: {
      parameters: {
        body: {
          /** 确认信息 */
          request: definitions["marketing.FlashConfirmReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/inventories/deduct": {
    post: {
      parameters: {
        body: {
          /** 扣减请求 */
          req: definitions["inventory.DeductStockReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["inventory.Inventory"];
          };
        };
      };
    };
  };
  "/api/v1/inventories/lock": {
    post: {
      parameters: {
        body: {
          /** 预占请求 */
          req: definitions["inventory.LockStockReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["inventory.Inventory"];
          };
        };
      };
    };
  };
  "/api/v1/inventories/logs": {
    get: {
      parameters: {
        query: {
          /** SKU ID */
          sku_id: number;
          /** 变更类型 */
          change_type?: string;
          /** 页码 */
          page?: number;
          /** 每页条数 */
          size?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["inventory.InventoryLogListResult"];
          };
        };
      };
    };
  };
  "/api/v1/inventories/restock": {
    post: {
      parameters: {
        body: {
          /** 入库请求 */
          req: definitions["inventory.RestockReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["inventory.Inventory"];
          };
        };
      };
    };
  };
  "/api/v1/inventories/stock": {
    get: {
      parameters: {
        query: {
          /** SKU ID */
          sku_id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["inventory.Inventory"];
          };
        };
      };
    };
  };
  "/api/v1/inventories/unlock": {
    post: {
      parameters: {
        body: {
          /** 释放请求 */
          req: definitions["inventory.UnlockStockReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["inventory.Inventory"];
          };
        };
      };
    };
  };
  "/api/v1/notifications": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          size?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["base.NotificationListResult"];
          };
        };
      };
    };
  };
  "/api/v1/notifications/readall": {
    put: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/notifications/system": {
    post: {
      parameters: {
        body: {
          /** 系统通知 */
          request: definitions["base.SendSystemNotificationReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/notifications/unread": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["base.UnreadCountResp"];
          };
        };
      };
    };
  };
  "/api/v1/notifications/{id}": {
    delete: {
      parameters: {
        path: {
          /** 通知ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/notifications/{id}/read": {
    put: {
      parameters: {
        path: {
          /** 通知ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/orders": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          size?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["trade.OrderListResult"];
          };
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 订单信息 */
          request: definitions["trade.CreateOrderReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["trade.Order"];
          };
        };
      };
    };
  };
  "/api/v1/orders/{order_no}": {
    get: {
      parameters: {
        path: {
          /** 订单号 */
          order_no: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["trade.OrderDetailResponse"];
          };
        };
      };
    };
  };
  "/api/v1/orders/{order_no}/status": {
    put: {
      parameters: {
        path: {
          /** 订单号 */
          order_no: string;
        };
        body: {
          /** 状态信息 */
          request: definitions["trade.UpdateOrderStatusReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["trade.Order"];
          };
        };
      };
    };
  };
  "/api/v1/payments": {
    post: {
      parameters: {
        body: {
          /** 支付信息 */
          request: definitions["trade.CreatePaymentReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["trade.Payment"];
          };
        };
      };
    };
  };
  "/api/v1/payments/callback": {
    post: {
      parameters: {
        body: {
          /** 回调信息 */
          request: definitions["trade.PaymentCallbackReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/payments/refund": {
    post: {
      parameters: {
        body: {
          /** 退款信息 */
          request: definitions["trade.CreateRefundReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/payments/{id}": {
    get: {
      parameters: {
        path: {
          /** 支付ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["trade.Payment"];
          };
        };
      };
    };
  };
  "/api/v1/permissions": {
    get: {
      parameters: {
        query: {
          category?: string;
          /** 页码，最小 1 */
          page?: number;
          resource?: string;
          role_id?: number;
          /** 每页条数，范围 1..1000 */
          size?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.PermissionListResult"];
          };
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 权限信息 */
          request: definitions["user.CreatePermissionReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.Permission"];
          };
        };
      };
    };
  };
  "/api/v1/permissions/check": {
    post: {
      parameters: {
        body: {
          /** 权限检查 */
          request: definitions["user.CheckPermissionsReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.CheckPermissionsResult"];
          };
        };
      };
    };
  };
  "/api/v1/permissions/roles/{role_id}": {
    get: {
      parameters: {
        path: {
          /** 角色ID */
          role_id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.Permission"][];
          };
        };
      };
    };
    post: {
      parameters: {
        path: {
          /** 角色ID */
          role_id: number;
        };
        body: {
          /** 权限ID列表 */
          request: definitions["user.AssignPermissionsReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** 角色ID */
          role_id: number;
        };
        body: {
          /** 权限ID列表 */
          request: definitions["user.AssignPermissionsReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/permissions/{id}": {
    get: {
      parameters: {
        path: {
          /** 权限ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.Permission"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          /** 权限ID */
          id: number;
        };
        body: {
          /** 权限信息 */
          request: definitions["user.UpdatePermissionReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.Permission"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** 权限ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/products": {
    get: {
      parameters: {
        query: {
          /** 每页条数 */
          size?: number;
          /** 游标（首次请求不传，后续使用上次返回的 cursor） */
          cursor?: string;
          /** 商品名称模糊搜索 */
          name?: string;
          /** 类目ID */
          category_id?: number;
          /** 品牌ID */
          brand_id?: number;
          /** 状态 0-草稿 1-待审 2-上架 3-下架 4-封禁 */
          status?: number;
          /** 最低价格（分） */
          price_min?: number;
          /** 最高价格（分） */
          price_max?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.SPUListResult"];
          };
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 商品信息（含 SKU 和属性） */
          product: definitions["product.CreateSPUReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.SPU"];
          };
        };
      };
    };
  };
  "/api/v1/products/{id}": {
    get: {
      parameters: {
        path: {
          /** 商品ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.SPUDetailResponse"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          /** 商品ID */
          id: number;
        };
        body: {
          /** 商品信息 */
          product: definitions["product.UpdateSPUReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.SPU"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** 商品ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: { [key: string]: string };
          };
        };
      };
    };
  };
  "/api/v1/products/{id}/rating": {
    get: {
      parameters: {
        path: {
          /** 商品SPU ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["review.ReviewRatingResp"];
          };
        };
      };
    };
  };
  "/api/v1/products/{id}/reviews": {
    get: {
      parameters: {
        path: {
          /** 商品SPU ID */
          id: number;
        };
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          size?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["review.ReviewListResult"];
          };
        };
      };
    };
  };
  "/api/v1/promotions": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          size?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["marketing.PromotionListResult"];
          };
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 促销信息 */
          request: definitions["marketing.CreatePromotionReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["marketing.Promotion"];
          };
        };
      };
    };
  };
  "/api/v1/promotions/{id}": {
    get: {
      parameters: {
        path: {
          /** 促销ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["marketing.Promotion"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          /** 促销ID */
          id: number;
        };
        body: {
          /** 促销信息 */
          request: definitions["marketing.UpdatePromotionReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["marketing.Promotion"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** 促销ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/promotions/{id}/detail": {
    get: {
      parameters: {
        path: {
          /** 促销ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["marketing.PromotionDetailResponse"];
          };
        };
      };
    };
  };
  "/api/v1/reviews": {
    post: {
      parameters: {
        body: {
          /** 评价信息 */
          request: definitions["review.CreateReviewReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["review.ReviewResp"];
          };
        };
      };
    };
  };
  "/api/v1/reviews/me": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          size?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["review.ReviewListResult"];
          };
        };
      };
    };
  };
  "/api/v1/reviews/{id}": {
    delete: {
      parameters: {
        path: {
          /** 评价ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/roles": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          size?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.RoleListResult"];
          };
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 角色信息 */
          request: definitions["user.CreateRoleReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.Role"];
          };
        };
      };
    };
  };
  "/api/v1/roles/{id}": {
    get: {
      parameters: {
        path: {
          /** 角色ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.Role"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          /** 角色ID */
          id: number;
        };
        body: {
          /** 角色信息 */
          request: definitions["user.UpdateRoleReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.Role"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** 角色ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/skus": {
    get: {
      parameters: {
        query: {
          /** 产品 ID */
          product_id?: number;
          /** SKU 编码 */
          sku_code?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.SKU"][];
          };
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** SKU 信息 */
          request: definitions["product.CreateSKUReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.SKU"];
          };
        };
      };
    };
  };
  "/api/v1/skus/code/:code": {
    get: {
      parameters: {
        path: {
          /** SKU 编码 */
          code: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.SKU"];
          };
        };
      };
    };
  };
  "/api/v1/skus/{id}": {
    get: {
      parameters: {
        path: {
          /** SKU ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.SKU"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          /** SKU ID */
          id: number;
        };
        body: {
          /** SKU 信息 */
          request: definitions["product.UpdateSKUReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["product.SKU"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** SKU ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/users": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          size?: number;
          /** 状态 */
          status?: number;
          /** 关键字（用户名/邮箱/手机号/昵称） */
          keyword?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.UserListResult"];
          };
        };
      };
    };
  };
  "/api/v1/users/info": {
    put: {
      parameters: {
        body: {
          /** 个人信息 */
          request: definitions["user.UpdateUserInfoReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/users/profile": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["user.UserProfileResponse"];
          };
        };
      };
    };
  };
  "/api/v1/users/{user_id}/roles": {
    post: {
      parameters: {
        path: {
          /** 用户ID */
          user_id: number;
        };
        body: {
          /** 角色ID */
          request: definitions["user.AssignRoleReq"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/users/{user_id}/roles/{role_id}": {
    delete: {
      parameters: {
        path: {
          /** 用户ID */
          user_id: number;
          /** 角色ID */
          role_id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
      };
    };
  };
  "/api/v1/ws": {
    /** 将HTTP连接升级为WebSocket连接，支持断线重连时携带last_seq参数 */
    get: {
      parameters: {
        query: {
          /** JWT Token */
          token: string;
          /** 最后收到的消息序列号（重连时使用） */
          last_seq?: number;
        };
      };
      responses: {
        /** WebSocket连接建立成功 */
        101: unknown;
        /** 请求参数错误 */
        400: unknown;
        /** 未授权 */
        401: unknown;
      };
    };
  };
  "/api/v1/ws/reconnect": {
    /** 客户端重连时提交lastSeq，服务端返回需要补发的消息 */
    post: {
      parameters: {
        header: {
          /** Bearer Token */
          Authorization: string;
        };
        body: {
          /** 重连请求 */
          request: definitions["dto.ReconnectRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["dto.ReconnectResponse"];
          };
        };
        /** 请求参数错误 */
        400: unknown;
        /** 未授权 */
        401: unknown;
      };
    };
  };
  "/api/v1/ws/session": {
    /** 获取当前用户的WebSocket会话信息，包括最后收到的消息序列号等 */
    get: {
      parameters: {
        header: {
          /** Bearer Token */
          Authorization: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["dto.SessionResponse"];
          };
        };
        /** 未授权 */
        401: unknown;
      };
    };
  };
  "/api/v1/ws/stats": {
    /** 获取当前WebSocket在线用户数和连接数 */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"] & {
            data?: definitions["dto.OnlineStatsResponse"];
          };
        };
      };
    };
  };
  "/api/v1/ws/test/push": {
    /** 向WebSocket客户端推送一条测试消息，用于调试 */
    post: {
      parameters: {
        header: {
          /** Bearer Token */
          Authorization: string;
        };
        body: {
          /** 测试消息 */
          request: definitions["ws.TestPushRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["response.Response"];
        };
        /** 未授权 */
        401: unknown;
      };
    };
  };
}

export interface definitions {
  "base.NotificationListResult": {
    list?: definitions["base.NotificationResp"][];
    total?: number;
  };
  "base.NotificationResp": {
    category?: number;
    channel?: number;
    content?: string;
    content_template?: string;
    created_at?: number;
    created_by?: number;
    icon_url?: string;
    id?: number;
    is_processed?: boolean;
    is_read?: boolean;
    priority?: number;
    process_result?: string;
    processed_at?: number;
    read_at?: number;
    redirect_url?: string;
    target_id?: number;
    target_type?: string;
    template_params?: string;
    title?: string;
    updated_at?: number;
    user_id?: number;
  };
  "base.SendSystemNotificationReq": {
    content: string;
    title: string;
    user_id?: number;
  };
  "base.UnreadCountResp": {
    count?: number;
  };
  "dashboard.CategoryDistDTO": {
    category?: string;
    value?: number;
  };
  "dashboard.DashboardResponse": {
    category_dist?: definitions["dashboard.CategoryDistDTO"][];
    inventory_status_dist?: definitions["dashboard.StatusDistDTO"][];
    order_status_dist?: definitions["dashboard.StatusDistDTO"][];
    order_trend?: definitions["dashboard.OrderTrendDTO"][];
    payment_method_dist?: definitions["dashboard.MethodDistDTO"][];
    summary?: definitions["dashboard.SummaryDTO"];
    top_products?: definitions["dashboard.TopProductDTO"][];
  };
  "dashboard.MethodDistDTO": {
    label?: string;
    method?: string;
    value?: number;
  };
  "dashboard.OrderTrendDTO": {
    amount?: number;
    count?: number;
    date?: string;
  };
  "dashboard.StatusDistDTO": {
    label?: string;
    status?: string;
    value?: number;
  };
  "dashboard.SummaryDTO": {
    low_stock_count?: number;
    total_orders?: number;
    total_products?: number;
    total_revenue?: number;
  };
  "dashboard.TopProductDTO": {
    amount?: number;
    count?: number;
    name?: string;
  };
  "dto.OnlineStatsResponse": {
    /** @description 连接数 */
    connections?: number;
    /** @description 在线用户数 */
    online_users?: number;
  };
  "dto.ReconnectRequest": {
    /** @description 客户端最后收到的消息序列号 */
    last_seq: number;
  };
  "dto.ReconnectResponse": {
    /** @description 缓存最大序列号 */
    cached_max_seq?: number;
    /** @description 缓存最小序列号 */
    cached_min_seq?: number;
    /** @description 服务端当前序列号 */
    current_seq?: number;
    /** @description 客户端上报的序列号 */
    last_seq?: number;
    /** @description 提示信息 */
    message?: string;
    /** @description 补发消息数量 */
    message_count?: number;
    /** @description 需要补发的消息列表 */
    messages?: unknown[];
    /** @description 是否需要全量同步 */
    need_full_sync?: boolean;
    /** @description 是否需要增量同步 */
    need_incremental?: boolean;
    /** @description 状态：ok, sync_required */
    status?: string;
  };
  "dto.SessionResponse": {
    /** @description 首次连接时间 */
    connected_at?: string;
    /** @description 会话是否存在 */
    exists?: boolean;
    /** @description 最后活跃时间 */
    last_active_at?: string;
    /** @description 最后收到的消息序列号 */
    last_seq?: number;
    /** @description 重连次数 */
    reconnect_count?: number;
    /** @description 用户ID */
    user_id?: number;
  };
  "inventory.DeductStockReq": {
    operator?: string;
    quantity: number;
    reference_id?: string;
    sku_id: number;
  };
  "inventory.Inventory": {
    created_at?: string;
    id?: number;
    in_transit?: number;
    last_counted_at?: string;
    last_counted_by?: string;
    max_threshold?: number;
    quantity?: number;
    reserved?: number;
    sku_id?: number;
    status?: string;
    threshold?: number;
    updated_at?: string;
    warehouse_id?: number;
  };
  "inventory.InventoryLog": {
    after_quantity?: number;
    after_reserved?: number;
    before_quantity?: number;
    before_reserved?: number;
    change_amount?: number;
    change_type?: string;
    created_at?: string;
    id?: number;
    note?: string;
    operator?: string;
    reference_id?: string;
    sku_id?: number;
    warehouse_id?: number;
  };
  "inventory.InventoryLogListResult": {
    list?: definitions["inventory.InventoryLog"][];
    total?: number;
  };
  "inventory.LockStockReq": {
    operator?: string;
    quantity: number;
    reference_id?: string;
    sku_id: number;
  };
  "inventory.RestockReq": {
    note?: string;
    operator?: string;
    quantity: number;
    reference_id?: string;
    sku_id: number;
    warehouse_id?: number;
  };
  "inventory.UnlockStockReq": {
    operator?: string;
    quantity: number;
    reference_id?: string;
    sku_id: number;
  };
  "marketing.ClaimCouponReq": {
    promotion_id: number;
  };
  "marketing.CreatePromotionReq": {
    /** @enum {integer} */
    benefit_type?: 1 | 2 | 3 | 4 | 5;
    benefit_value?: number;
    /** @enum {integer} */
    condition_type?: 1 | 2 | 3 | 4;
    condition_value?: number;
    end_time: string;
    /** @enum {integer} */
    is_stackable?: 0 | 1;
    per_user_limit?: number;
    /** @description Products */
    product_ids?: number[];
    promo_code?: string;
    promo_name: string;
    /** @enum {integer} */
    promo_type: 1 | 2 | 3 | 4 | 5 | 6;
    /** @description Rule */
    rule_name?: string;
    stack_priority?: number;
    start_time: string;
    total_quantity?: number;
  };
  "marketing.FlashBuyReq": {
    product_id: number;
    promotion_id: number;
    quantity: number;
    sku_id: number;
  };
  "marketing.FlashConfirmReq": {
    address_id?: number;
    token: string;
  };
  "marketing.Promotion": {
    created_at?: string;
    created_by?: number;
    end_time?: string;
    id?: number;
    per_user_limit?: number;
    promo_code?: string;
    promo_name?: string;
    promo_type?: number;
    rule_id?: number;
    start_time?: string;
    status?: number;
    total_quantity?: number;
    updated_at?: string;
    updated_by?: number;
    used_quantity?: number;
  };
  "marketing.PromotionDetailResponse": {
    created_at?: string;
    created_by?: number;
    end_time?: string;
    id?: number;
    per_user_limit?: number;
    products?: definitions["marketing.PromotionProductItem"][];
    promo_code?: string;
    promo_name?: string;
    promo_type?: number;
    rule?: definitions["marketing.PromotionRule"];
    rule_id?: number;
    start_time?: string;
    status?: number;
    total_quantity?: number;
    updated_at?: string;
    updated_by?: number;
    used_quantity?: number;
  };
  "marketing.PromotionListResult": {
    list?: definitions["marketing.Promotion"][];
    total?: number;
  };
  "marketing.PromotionProductItem": {
    category_id?: number;
    id?: number;
    main_image?: string;
    max_price?: number;
    min_price?: number;
    product_id?: number;
    product_type?: number;
    sales_count?: number;
    spu_name?: string;
    spu_status?: number;
    subtitle?: string;
    unit?: string;
  };
  "marketing.PromotionRule": {
    benefit_type?: number;
    benefit_value?: number;
    condition_type?: number;
    condition_value?: number;
    created_at?: string;
    created_by?: number;
    id?: number;
    is_stackable?: number;
    promotion_id?: number;
    rule_name?: string;
    stack_priority?: number;
    updated_at?: string;
    updated_by?: number;
  };
  "marketing.UpdatePromotionReq": {
    /** @enum {integer} */
    benefit_type?: 1 | 2 | 3 | 4 | 5;
    benefit_value?: number;
    /** @enum {integer} */
    condition_type?: 1 | 2 | 3 | 4;
    condition_value?: number;
    end_time?: string;
    /** @enum {integer} */
    is_stackable?: 0 | 1;
    per_user_limit?: number;
    promo_name?: string;
    rule_name?: string;
    stack_priority?: number;
    start_time?: string;
    /** @enum {integer} */
    status?: 1 | 2 | 3 | 4;
    total_quantity?: number;
  };
  "marketing.UseCouponReq": {
    order_id: number;
    user_promotion_id: number;
  };
  "marketing.UserPromotion": {
    acquire_time?: string;
    created_at?: string;
    created_by?: number;
    expire_time?: string;
    id?: number;
    order_id?: number;
    promotion_id?: number;
    queue_token?: string;
    status?: number;
    updated_at?: string;
    updated_by?: number;
    used_time?: string;
    user_id?: number;
  };
  "marketing.UserPromotionListResult": {
    list?: definitions["marketing.UserPromotion"][];
    total?: number;
  };
  "product.Attribute": {
    category_id?: number;
    created_at?: string;
    id?: number;
    /** @description 1-文本 2-单选 3-多选 4-数字 */
    input_type?: number;
    is_sku_spec?: number;
    name?: string;
    required?: number;
    searchable?: number;
    sort_order?: number;
    status?: number;
    unit?: string;
    updated_at?: string;
    /** @description 可选值 JSON 数组 */
    values?: string;
  };
  "product.Brand": {
    created_at?: string;
    description?: string;
    english_name?: string;
    first_letter?: string;
    id?: number;
    logo_url?: string;
    name?: string;
    sort_order?: number;
    status?: number;
    updated_at?: string;
  };
  "product.BrandListResult": {
    list?: definitions["product.Brand"][];
    total?: number;
  };
  "product.Category": {
    created_at?: string;
    icon_url?: string;
    id?: number;
    level?: number;
    name?: string;
    parent_id?: number;
    path?: string;
    sort_order?: number;
    status?: number;
    updated_at?: string;
  };
  "product.CategoryBrandDetail": {
    brand_id?: number;
    brand_name?: string;
    english_name?: string;
    first_letter?: string;
    logo_url?: string;
    sort_order?: number;
  };
  "product.CategoryListResult": {
    list?: definitions["product.Category"][];
    total?: number;
  };
  "product.CreateAttributeReq": {
    category_id: number;
    /** @enum {integer} */
    input_type?: 1 | 2 | 3 | 4;
    /** @enum {integer} */
    is_sku_spec?: 0 | 1;
    name: string;
    /** @enum {integer} */
    required?: 0 | 1;
    /** @enum {integer} */
    searchable?: 0 | 1;
    sort_order?: number;
    unit?: string;
    /** @description JSON */
    values?: string;
  };
  "product.CreateBrandReq": {
    description?: string;
    english_name?: string;
    first_letter?: string;
    logo_url?: string;
    name: string;
    sort_order?: number;
    /** @enum {integer} */
    status?: 0 | 1;
  };
  "product.CreateCategoryReq": {
    icon_url?: string;
    name: string;
    parent_id?: number;
    sort_order?: number;
  };
  "product.CreateProductAttrItem": {
    attribute_id: number;
    value: string;
  };
  "product.CreateSKUItem": {
    barcode?: string;
    cost_price?: number;
    height?: number;
    image?: string;
    length?: number;
    market_price?: number;
    max_purchase_qty?: number;
    min_purchase_qty?: number;
    price: number;
    sku_code: string;
    spec?: { [key: string]: string };
    volume?: number;
    weight?: number;
    width?: number;
  };
  "product.CreateSKUReq": {
    barcode?: string;
    cost_price?: number;
    height?: number;
    image?: string;
    length?: number;
    market_price?: number;
    price: number;
    product_id: number;
    sku_code: string;
    spec: string;
    volume?: number;
    weight?: number;
    width?: number;
  };
  "product.CreateSPUReq": {
    attributes?: definitions["product.CreateProductAttrItem"][];
    brand_id?: number;
    category_id: number;
    created_by?: string;
    description?: string;
    images?: string[];
    main_image: string;
    mobile_description?: string;
    name: string;
    skus: definitions["product.CreateSKUItem"][];
    sort_order?: number;
    subtitle?: string;
    unit?: string;
    video_url?: string;
  };
  "product.Description": {
    created_at?: string;
    description?: string;
    id?: number;
    mobile_description?: string;
    product_id?: number;
    updated_at?: string;
  };
  "product.ProductAttrResponse": {
    attribute_id?: number;
    attribute_name?: string;
    sort_order?: number;
    values?: string[];
  };
  "product.SKU": {
    available_quantity?: number;
    barcode?: string;
    cost_price?: number;
    created_at?: string;
    height?: number;
    id?: number;
    image?: string;
    inventory_status?: string;
    length?: number;
    market_price?: number;
    max_purchase_qty?: number;
    min_purchase_qty?: number;
    price?: number;
    product_id?: number;
    sku_code?: string;
    spec?: string;
    status?: number;
    updated_at?: string;
    volume?: number;
    weight?: number;
    width?: number;
  };
  "product.SPU": {
    brand_id?: number;
    category_id?: number;
    created_at?: string;
    created_by?: string;
    has_description?: number;
    id?: number;
    images?: string;
    main_image?: string;
    max_price?: number;
    min_price?: number;
    name?: string;
    rating_average?: number;
    rating_count?: number;
    sales_count?: number;
    sort_order?: number;
    status?: number;
    subtitle?: string;
    total_stock?: number;
    unit?: string;
    updated_at?: string;
    updated_by?: string;
    video_url?: string;
  };
  "product.SPUDetailResponse": {
    attributes?: definitions["product.ProductAttrResponse"][];
    brand_id?: number;
    category_id?: number;
    created_at?: string;
    created_by?: string;
    description?: definitions["product.Description"];
    has_description?: number;
    id?: number;
    images?: string;
    main_image?: string;
    max_price?: number;
    min_price?: number;
    name?: string;
    rating_average?: number;
    rating_count?: number;
    sales_count?: number;
    skus?: definitions["product.SKU"][];
    sort_order?: number;
    status?: number;
    subtitle?: string;
    total_stock?: number;
    unit?: string;
    updated_at?: string;
    updated_by?: string;
    video_url?: string;
  };
  "product.SPUListResult": {
    cursor?: string;
    has_more?: boolean;
    list?: definitions["product.SPU"][];
  };
  "product.SetCategoryBrandsReq": {
    brand_ids: number[];
    sort_order?: number;
  };
  "product.UpdateAttributeReq": {
    /** @enum {integer} */
    input_type?: 1 | 2 | 3 | 4;
    /** @enum {integer} */
    is_sku_spec?: 0 | 1;
    name?: string;
    /** @enum {integer} */
    required?: 0 | 1;
    /** @enum {integer} */
    searchable?: 0 | 1;
    sort_order?: number;
    /** @enum {integer} */
    status?: 0 | 1;
    unit?: string;
    values?: string;
  };
  "product.UpdateBrandReq": {
    description?: string;
    english_name?: string;
    first_letter?: string;
    logo_url?: string;
    name?: string;
    sort_order?: number;
    /** @enum {integer} */
    status?: 0 | 1;
  };
  "product.UpdateCategoryReq": {
    icon_url?: string;
    name?: string;
    sort_order?: number;
    /** @enum {integer} */
    status?: 0 | 1;
  };
  "product.UpdateSKUReq": {
    barcode?: string;
    cost_price?: number;
    height?: number;
    image?: string;
    length?: number;
    market_price?: number;
    price?: number;
    /** @enum {integer} */
    status?: 0 | 1;
    volume?: number;
    weight?: number;
    width?: number;
  };
  "product.UpdateSPUReq": {
    images?: string[];
    main_image?: string;
    name?: string;
    sort_order?: number;
    /** @enum {integer} */
    status?: 0 | 1 | 2 | 3 | 4;
    subtitle?: string;
    unit?: string;
    updated_by?: string;
    video_url?: string;
  };
  "response.Response": {
    code?: number;
    data?: unknown;
    message?: string;
    trace_id?: string;
  };
  "review.CreateReviewReq": {
    content?: string;
    is_anonymous?: boolean;
    logistics_rating?: number;
    order_id: number;
    order_item_id?: number;
    overall_rating: number;
    quality_rating?: number;
    service_rating?: number;
    sku_id?: number;
    spu_id: number;
  };
  "review.ModerateReviewReq": {
    reason?: string;
    /** @enum {integer} */
    status: 1 | 2;
  };
  "review.ReplyReviewReq": {
    content: string;
  };
  "review.ReviewListResult": {
    list?: definitions["review.ReviewResp"][];
    total?: number;
  };
  "review.ReviewRatingResp": {
    avg_logistics_rating?: number;
    avg_overall_rating?: number;
    avg_quality_rating?: number;
    avg_service_rating?: number;
    rating_1_count?: number;
    rating_2_count?: number;
    rating_3_count?: number;
    rating_4_count?: number;
    rating_5_count?: number;
    spu_id?: number;
    total_reviews?: number;
    with_media_count?: number;
  };
  "review.ReviewResp": {
    content?: string;
    created_at?: number;
    helpful_count?: number;
    id?: number;
    is_anonymous?: boolean;
    like_count?: number;
    logistics_rating?: number;
    order_id?: number;
    order_item_id?: number;
    overall_rating?: number;
    quality_rating?: number;
    reject_reason?: string;
    reply_count?: number;
    service_rating?: number;
    sku_id?: number;
    spu_id?: number;
    status?: number;
    updated_at?: number;
    user_id?: number;
  };
  "trade.AddItemReq": {
    quantity: number;
    sku_id: number;
  };
  "trade.AddressInfo": {
    city?: string;
    consignee: string;
    detail_addr?: string;
    district?: string;
    phone: string;
    province?: string;
    zip_code?: string;
  };
  "trade.Cart": {
    created_at?: string;
    expired_at?: string;
    id?: number;
    item_count?: number;
    session_id?: string;
    total_amount?: number;
    updated_at?: string;
    user_id?: number;
  };
  "trade.CreateOrderItem": {
    quantity: number;
    sku_id: number;
  };
  "trade.CreateOrderReq": {
    address: definitions["trade.AddressInfo"];
    buyer_remark?: string;
    coupon_id?: number;
    items: definitions["trade.CreateOrderItem"][];
    source?: string;
  };
  "trade.CreatePaymentReq": {
    amount: number;
    channel?: string;
    order_id: number;
    order_no: string;
    order_type?: string;
    payment_method: string;
  };
  "trade.CreateRefundReq": {
    amount: number;
    payment_no: string;
    reason?: string;
  };
  "trade.Order": {
    buyer_remark?: string;
    city?: string;
    closed_at?: string;
    completed_at?: string;
    consignee?: string;
    coupon_id?: number;
    coupon_snapshot?: string;
    created_at?: string;
    delivered_at?: string;
    detail_addr?: string;
    discount_amount?: number;
    district?: string;
    id?: number;
    order_no?: string;
    paid_at?: string;
    pay_amount?: number;
    payment_method?: string;
    payment_status?: string;
    phone?: string;
    province?: string;
    seller_remark?: string;
    shipped_at?: string;
    shipping_fee?: number;
    source?: string;
    status?: string;
    total_amount?: number;
    updated_at?: string;
    user_id?: number;
    zip_code?: string;
  };
  "trade.OrderDetailResponse": {
    buyer_remark?: string;
    city?: string;
    closed_at?: string;
    completed_at?: string;
    consignee?: string;
    coupon_id?: number;
    coupon_snapshot?: string;
    created_at?: string;
    delivered_at?: string;
    detail_addr?: string;
    discount_amount?: number;
    district?: string;
    id?: number;
    items?: definitions["trade.OrderItem"][];
    order_no?: string;
    paid_at?: string;
    pay_amount?: number;
    payment_method?: string;
    payment_status?: string;
    phone?: string;
    province?: string;
    seller_remark?: string;
    shipped_at?: string;
    shipping_fee?: number;
    source?: string;
    status?: string;
    total_amount?: number;
    updated_at?: string;
    user_id?: number;
    zip_code?: string;
  };
  "trade.OrderItem": {
    created_at?: string;
    id?: number;
    image?: string;
    order_id?: number;
    order_no?: string;
    price?: number;
    product_id?: number;
    product_name?: string;
    quantity?: number;
    refund_amount?: number;
    refund_status?: string;
    sku_code?: string;
    sku_id?: number;
    sku_spec?: string;
    subtotal?: number;
    updated_at?: string;
  };
  "trade.OrderListResult": {
    list?: definitions["trade.Order"][];
    total?: number;
  };
  "trade.Payment": {
    amount?: number;
    channel?: string;
    created_at?: string;
    currency?: string;
    failure_reason?: string;
    id?: number;
    order_id?: number;
    order_no?: string;
    order_type?: string;
    paid_at?: string;
    payment_method?: string;
    payment_no?: string;
    status?: string;
    transaction_id?: string;
    updated_at?: string;
  };
  "trade.PaymentCallbackReq": {
    channel?: string;
    failure_reason?: string;
    payment_no: string;
    raw_body?: string;
    /** @enum {string} */
    status: "success" | "failed";
    transaction_id: string;
  };
  "trade.UpdateItemReq": {
    quantity?: number;
    sku_id: number;
  };
  "trade.UpdateOrderStatusReq": {
    note?: string;
    /** @enum {string} */
    status: "cancelled" | "shipped" | "delivered" | "completed";
  };
  "user.Address": {
    city?: string;
    consignee?: string;
    country?: string;
    created_at?: string;
    detail?: string;
    district?: string;
    id?: number;
    is_default?: boolean;
    phone?: string;
    province?: string;
    tag?: string;
    updated_at?: string;
    user_id?: number;
    zip_code?: string;
  };
  "user.AddressListResult": {
    list?: definitions["user.Address"][];
    total?: number;
  };
  "user.AssignPermissionsReq": {
    permission_ids: number[];
  };
  "user.AssignRoleReq": {
    role_id: number;
  };
  "user.CheckPermissionsReq": {
    permission_names: string[];
  };
  "user.CheckPermissionsResult": {
    permissions?: { [key: string]: boolean };
  };
  "user.CreateAddressReq": {
    city: string;
    consignee: string;
    country?: string;
    detail: string;
    district: string;
    is_default?: boolean;
    phone: string;
    province: string;
    /** @enum {string} */
    tag?: "home" | "office" | "company" | "other";
    zip_code?: string;
  };
  "user.CreatePermissionReq": {
    action: string;
    category?: string;
    description?: string;
    display_name: string;
    name: string;
    resource: string;
    sort_order?: number;
  };
  "user.CreateRoleReq": {
    description?: string;
    display_name: string;
    is_system?: boolean;
    name: string;
    sort_order?: number;
    /** @enum {integer} */
    status?: 0 | 1;
  };
  "user.LoginResponse": {
    access_token?: string;
    expires_at?: number;
    is_new_user?: boolean;
    refresh_token?: string;
    token_type?: string;
    user_id?: number;
    username?: string;
  };
  "user.PasswordLoginReq": {
    password: string;
    username: string;
  };
  "user.Permission": {
    action?: string;
    category?: string;
    created_at?: string;
    description?: string;
    display_name?: string;
    id?: number;
    name?: string;
    resource?: string;
    sort_order?: number;
    status?: number;
    updated_at?: string;
  };
  "user.PermissionListResult": {
    list?: definitions["user.Permission"][];
    total?: number;
  };
  "user.RefreshTokenReq": {
    refresh_token: string;
  };
  "user.RegisterReq": {
    email?: string;
    password?: string;
    phone?: string;
    provider: string;
    username?: string;
  };
  "user.Role": {
    created_at?: string;
    description?: string;
    display_name?: string;
    id?: number;
    is_system?: boolean;
    name?: string;
    sort_order?: number;
    status?: number;
    updated_at?: string;
  };
  "user.RoleListResult": {
    list?: definitions["user.Role"][];
    total?: number;
  };
  "user.TokenResponse": {
    access_token?: string;
    expires_at?: number;
    refresh_token?: string;
    token_type?: string;
  };
  "user.UpdateAddressReq": {
    city?: string;
    consignee?: string;
    country?: string;
    detail?: string;
    district?: string;
    is_default?: boolean;
    phone?: string;
    province?: string;
    /** @enum {string} */
    tag?: "home" | "office" | "company" | "other";
    zip_code?: string;
  };
  "user.UpdatePermissionReq": {
    category?: string;
    description?: string;
    display_name?: string;
    sort_order?: number;
    /** @enum {integer} */
    status?: 0 | 1;
  };
  "user.UpdateRoleReq": {
    description?: string;
    display_name?: string;
    sort_order?: number;
    /** @enum {integer} */
    status?: 0 | 1;
  };
  "user.UpdateUserInfoReq": {
    avatar?: string;
    bio?: string;
    birthday?: string;
    city?: string;
    country?: string;
    /** @enum {integer} */
    gender?: 0 | 1 | 2;
    language?: string;
    nickname?: string;
    province?: string;
    timezone?: string;
    zip_code?: string;
  };
  "user.UserInfoResponse": {
    bio?: string;
    birthday?: string;
    city?: string;
    country?: string;
    gender?: number;
    language?: string;
    province?: string;
    timezone?: string;
    zip_code?: string;
  };
  "user.UserListItem": {
    avatar?: string;
    created_at?: string;
    email?: string;
    email_verified?: boolean;
    id?: number;
    last_login_at?: string;
    last_login_ip?: string;
    nickname?: string;
    phone?: string;
    phone_verified?: boolean;
    register_ip?: string;
    register_source?: string;
    roles?: definitions["user.UserRoleBrief"][];
    status?: number;
    updated_at?: string;
    username?: string;
  };
  "user.UserListResult": {
    list?: definitions["user.UserListItem"][];
    total?: number;
  };
  "user.UserProfileResponse": {
    avatar?: string;
    email?: string;
    email_verified?: boolean;
    id?: number;
    nickname?: string;
    phone?: string;
    phone_verified?: boolean;
    status?: number;
    user_info?: definitions["user.UserInfoResponse"];
    username?: string;
  };
  "user.UserRoleBrief": {
    display_name?: string;
    id?: number;
    name?: string;
  };
  "ws.TestPushRequest": {
    /** @description 级别: info/warning/error */
    level?: string;
    /** @description 通知内容 */
    message: string;
    /** @description 目标: all(默认) 或 user_id */
    target?: string;
    /** @description 通知标题 */
    title: string;
  };
}

export interface operations {}

export interface external {}
